[package]
authors = ["Alex Martin <martinak0@protonmail.com>"]
license = "BSD-3 Clause"
edition = "2018"
name = "reme"
version = "0.1.0"

[dependencies]
datetime = "*"
discord = "*"
lazy_static = "*"
sqlite = "*"
